CREATE TABLE IF NOT EXISTS public.scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_name TEXT NOT NULL,
    name TEXT NOT NULL,
    score INTEGER NOT NULL,
    meters REAL NOT NULL DEFAULT 0.0,
    room_code TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS) policies si es necesario
ALTER TABLE public.scores ENABLE ROW LEVEL SECURITY;

-- Crear política para permitir inserciones públicas (anon)
CREATE POLICY "Allow public inserts" ON public.scores FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public reads" ON public.scores FOR SELECT USING (true);

-- Tabla para almacenar códigos de sala
CREATE TABLE IF NOT EXISTS public.rooms (
    code TEXT PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public inserts" ON public.rooms FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public reads" ON public.rooms FOR SELECT USING (true);
